import os
#print(dir(os))
# print(os.getcwd())
# os.chdir("c://")
# print(os.getcwd())
# f=open('harry-ex.txt')
# print(os.listdir)
#print(os.listdir("D://"))
#os.mkdir("THIS")
#os.makedirs("Book/Chapter")
#os.rename("kunal.txt","kunal.py") #pratik.txt
# #print(os.environ.get('path'))
# print(os.path.join("D://","Pratik.txt"))
# print(os.path.exists("D://pratik.txt"))
# print(os.path.isfile("D://pratik.txt"))